generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: backend-secrets
    namespace: room-occupancy-manager--latest
    literals:
      - SERVER_PORT=8080
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY_STORE=classpath:keystore/dev.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
      - NATIVE_REFLECTION_CONFIGURATION_GENERATOR_ENABLED=false
